<!DOCTYPE html>
<html lang="en"><head>
<script src="agentic-research-workflows_files/libs/clipboard/clipboard.min.js"></script>
<script src="agentic-research-workflows_files/libs/quarto-html/tabby.min.js"></script>
<script src="agentic-research-workflows_files/libs/quarto-html/popper.min.js"></script>
<script src="agentic-research-workflows_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="agentic-research-workflows_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="agentic-research-workflows_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="agentic-research-workflows_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Chris Sweet">
  <meta name="author" content="Charles Vardeman">
  <meta name="author" content="Priscila Moreira">
  <meta name="author" content="James Sweet">
  <meta name="dcterms.date" content="2026-01-01">
  <title>Agentic research workflows</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="agentic-research-workflows_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="agentic-research-workflows_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="agentic-research-workflows_files/libs/revealjs/dist/theme/quarto-00d918fe3ce335e2c1d542d2fc53de8b.css">
  <link href="agentic-research-workflows_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="agentic-research-workflows_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="agentic-research-workflows_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="agentic-research-workflows_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <style>
  .reveal .ed-img{ display:block; margin:0 auto; max-width:100%; max-height:400px; border:1px solid #d8cfb6; border-radius:4px; }
  .reveal #title-slide .quarto-title-authors{ transform:translateX(-2em); }
  .reveal .ed-quote{ font-size:1.15em; font-weight:600; color:#14213d; line-height:1.35; border-left:5px solid #b8860b; padding:.15em 0 .15em .7em; margin:.35em 0; font-style:italic; }
  .reveal .ed-quote .src{ display:block; font-size:.42em; font-style:normal; color:#8a7a4a; margin-top:.4em; }
  .reveal .ed-tip{ background:rgba(13,102,110,.09); border-left:5px solid #0d666e; border-radius:6px; padding:.3em .75em; margin:.35em 0; font-size:.82em; }
  .reveal .ed-tip strong{ color:#0d666e; text-transform:uppercase; letter-spacing:.04em; }
  .reveal .ed-tip code{ background:rgba(13,102,110,.12); color:#0d666e; padding:0 .25em; border-radius:3px; }
  .reveal .ed-probs-h{ text-align:center; color:#a13a30; font-weight:800; text-transform:uppercase; letter-spacing:.08em; font-size:.5em; margin:.35em 0 .15em; }
  .reveal .ed-probs{ display:flex; flex-direction:column; gap:.45em; }
  .reveal .ed-prob{ background:rgba(161,58,48,.08); border-left:5px solid #a13a30; border-radius:6px; padding:.4em .75em; font-size:.82em; line-height:1.35; text-align:left; }
  .reveal .ed-prob strong{ color:#a13a30; }
  .reveal .ed-prob .ex{ font-size:.86em; margin-top:.4em; color:#5a4a4a; }
  .reveal .ed-prob .ex b{ color:#a13a30; }
  .reveal .ed-fig{ text-align:left; }
  .reveal .ed-req{ width:100%; border-collapse:collapse; font-size:.52em; }
  .reveal .ed-req th{ text-align:left; font-size:.85em; text-transform:uppercase; letter-spacing:.05em; color:#b8860b; border-bottom:2px solid #b8860b; padding:.3em .5em; }
  .reveal .ed-req td{ padding:.45em .5em; border-bottom:1px solid #e2d3a8; vertical-align:top; }
  .reveal .ed-req .req{ font-weight:700; color:#14213d; }
  .reveal .ed-req .prac{ color:#0d666e; font-weight:600; }
  .reveal .ed-logcard{ background:#fbf9f3; border:1px solid #d8cfb6; border-left:4px solid #b8860b; border-radius:6px; padding:.6em .8em; font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.64em; line-height:1.45; color:#2c2c2c; box-shadow:0 2px 10px rgba(0,0,0,.07); }
  .reveal .ed-logcard .h{ font-weight:700; color:#14213d; }
  .reveal .ed-logcard .by{ color:#8a7a4a; font-style:italic; }
  .reveal .ed-logcard ul{ margin:.35em 0 0; padding-left:1.05em; }
  .reveal .ed-logcard li{ margin-bottom:.3em; }
  .reveal .ed-cap{ display:block; margin-top:.35em; font-size:.9em; font-style:italic; color:#8a7a4a; }
  .reveal .ed-deadcard{ background:#f7eeee; border:1px solid #d8b6b6; border-left:4px solid #a13a30; border-radius:6px; padding:.5em .7em; margin-top:.6em; font-family:ui-monospace,Menlo,monospace; font-size:.64em; line-height:1.45; color:#3a2222; }
  .reveal .ed-deadcard .h{ font-weight:800; color:#a13a30; letter-spacing:.08em; text-transform:uppercase; font-size:.85em; }
  .reveal .ed-term{ background:#0b1020; border:1px solid #24314c; border-radius:8px; padding:.8em 1em; font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.68em; line-height:1.5; color:#cdd6e4; box-shadow:0 10px 28px rgba(0,0,0,.45); }
  .reveal .ed-term .cmd{ color:#7683a0; }
  .reveal .ed-term .mut{ color:#e0a44b; font-weight:700; }
  .reveal .ed-term .fail{ color:#ff6b6b; font-weight:700; }
  .reveal .ed-term .rev{ color:#7683a0; }
  .reveal .ed-term .pass{ color:#6ee0a0; font-weight:700; }
  .reveal .ed-tmpl{ display:grid; grid-template-columns:1fr 1fr; gap:.55em; font-size:.8em; text-align:left; }
  .reveal .ed-card{ background:#fff; border:1px solid #d8cfb6; border-top:3px solid #b8860b; border-radius:6px; padding:.55em .65em; box-shadow:0 2px 8px rgba(0,0,0,.06); }
  .reveal .ed-card .t{ font-weight:800; color:#b8860b; text-transform:uppercase; letter-spacing:.04em; font-size:.85em; margin-bottom:.35em; }
  .reveal .ed-card .kv{ margin:.12em 0; } .reveal .ed-card .kv b{ color:#14213d; }
  .reveal .ed-card.mono{ font-family:ui-monospace,Menlo,monospace; }
  .reveal .ed-mini{ width:100%; border-collapse:collapse; font-family:ui-monospace,Menlo,monospace; }
  .reveal .ed-mini th{ text-align:left; color:#b8860b; border-bottom:1px solid #d8cfb6; padding:.12em .3em; font-size:.95em; }
  .reveal .ed-mini td{ padding:.12em .3em; border-bottom:1px solid #eee; color:#333; }
  .reveal .ed-surf{ display:flex; gap:.2em; } .reveal .ed-surf span{ flex:1; text-align:center; background:#eef1f7; border:1px solid #14213d; border-radius:3px; padding:.15em; font-size:.9em; color:#14213d; }
  .reveal .ed-surf span.frozen{ background:#f0ece0; color:#8a7a4a; border-color:#d8cfb6; }
  .reveal .ed-corr{ text-align:left; font-size:.5em; }
  .reveal .ed-corr li{ margin-bottom:.5em; }
  .reveal .ed-corr .ck{ color:#2c7a54; font-weight:800; }
  </style>
  <script>
  document.addEventListener('DOMContentLoaded', function () {
    function injectKicker() {
      var ts = document.getElementById('title-slide');
      if (!ts) { setTimeout(injectKicker, 100); return; }
      if (ts.querySelector('.title-kicker')) return;
      var k = document.createElement('div');
      k.className = 'title-kicker';
      k.textContent = 'Doing research with AI agents';
      ts.insertBefore(k, ts.firstChild);
    }
    injectKicker();
  });
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#14213d" class="quarto-title-block center">
  <h1 class="title">Agentic research workflows</h1>
  <p class="subtitle">An introduction to using Codex for research workflows<br>and getting a project-specific knowledge base started</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Chris Sweet 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Charles Vardeman 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Priscila Moreira 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
James Sweet 
</div>
</div>
</div>

  <p class="date">2026-01-01</p>
</section>
<section id="the-bottleneck-moved" class="slide level2 smaller">
<h2>The bottleneck moved</h2>
<p><span class="kicker">The problem with a fast, plausible collaborator</span></p>
<p>Research is a loop: hypothesize, write the code, analyze, test, revise, and go round again. Producing each result used to be the slow part.</p>
<p>AI now appears to remove that bottleneck. It writes complex code, carries a vast working knowledge of statistics and analysis methods, and returns test results ready to present.</p>
<div class="callout-highlight">
<p>So the bottleneck of research is no longer producing results. It is knowing which results deserve belief.</p>
</div>
<p><strong>Plausibility is the enemy.</strong> From our own project record, the AI describing its own failure, verbatim:</p>
<div class="ed-quote">
<p>“The worst failure of this project: I built a tractable proxy instead of the user’s hypothesis, and let loose language hide the substitution.” <span class="src">Lessons-Learned.md, project wiki, 2026-08-19, recorded by the AI and found on query</span></p>
</div>
<p>Nothing was wrong with the output. It ran, it passed, it read well. It just was not the thing we set out to know. We only caught it because the AI had written the failure into a durable memory we could go back and read.</p>
<div class="ed-tip">
<p><strong>Tip 1.</strong> Have the LLM record what it learns into a durable memory you keep and can read back, not a chat window that vanishes. The quote above is from ours.</p>
</div>
<aside class="notes">
<p>Open cold with the quote if comfortable. Land in the first minute: this failure was caught, recorded by the AI in its own words, and became a rule. End on the memory seed: we only know about it because it was written into a durable memory we could query, which is exactly what the rest of the deck builds. The talk is about the machinery that makes that the normal outcome, not a lucky catch. Do not name the domain yet; the problem is universal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-epistemic-discipline-is" class="slide level2 smaller">
<h2>What epistemic discipline is</h2>
<p><span class="kicker">Habits you already have, that AI speed breaks</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Epistemic discipline</strong> turns a produced result into something you actually <em>know</em>: justified, not merely generated. In practice, a few rules about what must be recorded, and carried with the claim, before it enters the record.</p>
<p>You already practice this. Each one is a standard scientific habit.</p>
</div><div class="column" style="width:50%;">
<table class="ed-req caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">The habit</th>
<th data-quarto-table-cell-role="th">What you already call it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="req">Provenance.</span> a claim carries where it came from, and its scope</td>
<td class="prac">citation</td>
</tr>
<tr class="even">
<td><span class="req">Durable memory.</span> what was tried, decided, and abandoned is written down</td>
<td class="prac">a lab notebook</td>
</tr>
<tr class="odd">
<td><span class="req">Pre-commitment.</span> targets declared before the data arrives</td>
<td class="prac">pre-registration</td>
</tr>
</tbody>
</table>
</div></div>
<div class="ed-probs-h">Why it breaks with AI</div>
<div class="ed-probs">
<div class="ed-prob">The habits live in your head and in a chat window that vanishes when the session ends. At AI speed they are the first thing skipped: when a result arrives in minutes, the provenance and the notes are what get dropped.</div>
<div class="ed-prob">And AI discards and regenerates work at each step, instead of a small, preserving <em>epsilon</em> step that keeps what was already verified.<div class="ex"><b>Seen here:</b> asked to consolidate three reports into one paper, it regenerated rather than preserved, and the draft did not even describe the framework the reports exist to present. Filed as a dead end.</div></div>
</div>
<div class="callout-highlight">
<p>So stop <em>remembering</em> the discipline. Its key element is <span style="color:#b8860b; font-weight:800; font-size:1.15em">memory</span>: move the provenance and the notes out of your head into an artifact the AI writes and you read. Get the memory right and the discipline holds.</p>
</div>
<aside class="notes">
<p>This is the motivation slide; its job is to hand off to the wiki. The claim is not that AI needs a new epistemology; it is that AI-speed research needs the old habits moved out of your head, because no one, human or AI, keeps habits at that pace. Dropped the fourth “witnessed failure / positive control” leg on purpose: it is testing vocabulary and points at gates, not the durable memory this talk builds. Surviving example source: consolidation regenerated and lost the framework the reports exist to present (Capabilities-Ledger dead ends). The next slides name that artifact, an llm-wiki, and build one live in Codex.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-kind-of-memory" class="slide level2 smaller">
<h2>What kind of memory?</h2>
<p><span class="kicker">Five kinds, only one is durable and yours to read</span></p>
<p>An agent has several memories. Most are frozen, optional, scoped, or temporary. The question that matters: which one still holds your project’s knowledge after the session ends?</p>
<table class="ed-req caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">The memory</th>
<th data-quarto-table-cell-role="th">What it is</th>
<th data-quarto-table-cell-role="th">How long it lasts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="req">Embedded</span> (training)</td>
<td>the model's learned world knowledge</td>
<td class="prac">frozen at the cutoff</td>
</tr>
<tr class="even">
<td><span class="req">Local memories</span></td>
<td>optional machine-local cross-session store (Codex <code>/memories</code>)</td>
<td class="prac">off by default, empty here</td>
</tr>
<tr class="odd">
<td><span class="req">AGENTS.md</span></td>
<td>scoped instructions, loaded per folder at startup</td>
<td class="prac">rules, not a knowledge base</td>
</tr>
<tr class="even">
<td><span class="req">Session context</span></td>
<td>the live conversation and tool results</td>
<td class="prac">gone when the session ends</td>
</tr>
<tr class="odd">
<td><span class="req">llm-wiki</span></td>
<td>pages the agent writes and you read, in git</td>
<td class="prac">durable, versioned, yours</td>
</tr>
</tbody>
</table>
<div class="ed-probs"><div class="ed-prob"><b>And local memories are not yours to control.</b> The agent decides whether to write one, and can overwrite or delete it. There is no version history and no backup: if a memory is lost or silently changed, you cannot see what happened or roll it back.</div></div>
<div class="callout-highlight">
<p>Only the <strong>llm-wiki</strong> is durable <em>and under your control</em>: the agent writes it, you read it, and it lives in git, so every change is visible, reviewable, and reversible.</p>
</div>
<aside class="notes">
<p>Kinds of memory, verified on 2026-09-19 by asking the running Codex session, which inspected its own machine: embedded/parametric in the weights; a local cross-session memory feature (<code>~/.codex/memories_1.sqlite</code>, <code>/memories</code>) that exists but was empty here and is NOT a universal global memory; <code>AGENTS.md</code> scoped instructions loaded global-to-cwd at startup (none in this project); the session context window, bounded and lost after the session; and the llm-wiki, a separate human-readable git repo the agent reads and writes. The control point is the crux: local memories are agent-generated (Codex <code>memories.generate_memories</code> / <code>use_memories</code>), unversioned, and overwritable, so there is no audit trail or backup; the llm-wiki is git-backed, so writes are explicit, reviewable, and reversible. Do not call the local-memory feature “global.” Next slide defines the llm-wiki.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-an-llm-wiki-is" class="slide level2 smaller">
<h2>What an llm-wiki is</h2>
<p><span class="kicker">The memory the LLM writes and you read</span></p>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>Proposed by Andrej Karpathy</strong> (OpenAI founding member, former director of AI at Tesla)<strong>:</strong> dense, interlinked wiki pages as a <strong>persistent memory the LLM authors and maintains</strong>, kept as plain Markdown in version control.</li>
<li><strong>A read-write loop that compounds.</strong> The LLM <strong>reads the wiki at the start of a session to recall</strong> where things stand, and <strong>writes back at the end to remember</strong> what it learned. Each session builds on the last instead of starting cold.</li>
<li><strong>Auditable by you.</strong> Because it is Markdown in git, you can read exactly what the agent knows and see every change it makes.</li>
<li><strong>Portable as a knowledge bundle:</strong> you can share the whole knowledge base and another person’s LLM can read it.</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="ed-tip">
<p><strong>Trusted AI.</strong> The human stays in the loop: audit what the agent knows and check any claim at its source. When something is wrong, you catch it and direct the fix, which the agent makes and logs. Accountable and explainable, the trust our group builds toward, not a black box.</p>
</div>
</div></div>
<div class="callout-highlight">
<p>A persistent, compounding project memory the LLM writes and you read, not retrieval re-run from scratch on every question.</p>
</div>
<aside class="notes">
<p>Zoom into the winner from the memory ladder; do not re-argue the contrast, slide 3 did that. Three beats: (1) the definition and Karpathy provenance; (2) the read-write loop that compounds, read to recall at session start, write to remember at the end; (3) it is plain Markdown in git, so it is auditable and correctable. The one contrast worth keeping is “not RAG re-run per question.” Framing from llm-wiki.md (persistent, compounding artifact the LLM owns and writes, you read). Next: build one live in Codex.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="how-to-build-an-llm-wiki-with-codex" class="slide level2 smaller">
<h2>How to build an llm-wiki with Codex</h2>
<p><span class="kicker">The tutorial, run with students on 2026-09-15</span></p>
<div class="columns">
<div class="column" style="width:40%;">
<p>llm-wiki is a Gist from Andrej Karpathy, an idea rather than an implementation. Our implementation assumes the following:</p>
<ul>
<li>We assume <strong>project-based</strong> work, so there is a base GitHub repo for code, data, and artifacts.</li>
<li>By default we create the wiki as a <strong>GitHub wiki</strong>, a special repository GitHub uses for its wiki functionality, so you can view it in the online GitHub interface, shown here.</li>
<li>Other wiki destinations are available.</li>
</ul>
<div class="ed-tip">
<p>The next slides walk the whole process, built live in Codex: install, initialize, ingest a paper, run a real prediction, and record it as a durable wiki page.</p>
</div>
</div><div class="column" style="width:60%;">
<p><img class="ed-img" src="slide-assets/wiki-screenshot.png" alt="The finished codex-llm-wiki-test GitHub wiki: the Chignolin AlphaFold Prediction page with its 12-page sidebar"> <span class="ed-cap">github.com/chrissweet/codex-llm-wiki-test/wiki</span></p>
</div></div>
<aside class="notes">
<p>Transition. The rest is not slides, it is the thing itself. If running live is risky, these are captured screenshots of the same session. Keep it moving; the payoff slide (does it work) comes right after.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="demo-1-install-the-plugin-make-the-repo" class="slide level2 smaller">
<h2>Demo 1: install the plugin, make the repo</h2>
<p><span class="kicker">One marketplace, two commands</span></p>
<p>Our implementation of llm-wiki provides our own <strong>marketplace</strong>, a storefront for plugins, and we have versions for the AI harnesses Codex, Claude, and Cursor.</p>
<p>Install the plugin from the LA3D marketplace:</p>
<div class="ed-term"><div><span class="cmd">$ codex plugin marketplace add LA3D-LLM-Agents/llm-wiki-colab</span></div><div><span class="pass">Marketplace `llm-wiki-colab` added.</span></div><div><span class="cmd">$ codex plugin add llm-wiki@llm-wiki-colab</span></div><div><span class="pass">Added plugin `llm-wiki` from marketplace `llm-wiki-colab` (0.4.0).</span></div></div>
<p>Codex loads plugins at startup, so <strong>exit and restart Codex</strong>, and <strong>accept the plugin’s hooks</strong> when prompted. Then create the project repo:</p>
<div class="ed-term"><div><span class="cmd">$ gh repo create chrissweet/codex-llm-wiki-test --public</span></div><div><span class="pass">✓ Created repository chrissweet/codex-llm-wiki-test on GitHub</span></div></div>
<div class="ed-tip">
<p><strong>Same wiki, any harness.</strong> The identical plugin installs in Claude Code (<code>/plugin marketplace add</code>, <code>/plugin install</code>), Codex (<code>codex plugin marketplace add</code>, <code>codex plugin add</code>), and Cursor (<code>cursor-agent plugin marketplace add</code>).</p>
</div>
<aside class="notes">
<p>The marketplace is the LA3D-LLM-Agents/llm-wiki-colab repo; the plugin is llm-wiki. Restart and the hook-trust prompt are the two Codex-specific gotchas. The empty repo is where the wiki will attach.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="demo-2-initialize-the-wiki" class="slide level2 smaller">
<h2>Demo 2: initialize the wiki</h2>
<p><span class="kicker">wiki-init, GitHub-backed</span></p>
<p>Run the init skill and choose GitHub:</p>
<div class="ed-term"><div><span class="cmd">$ $llm-wiki:wiki-init</span></div><div><span class="rev">? storage backend →</span> <span class="mut">GitHub</span></div><div><span class="cmd">$ bash "$SKILL_DIRECTORY/scripts/init-wiki.sh" --github --agent "codex"</span></div><div><span class="pass">created .llm-wiki/  (own git repo, attached to the wiki remote)</span></div></div>
<p>It scaffolds <code>.llm-wiki/</code> as its own git repository, attaches it to the repository’s GitHub wiki remote, and writes the SCHEMA plus navigation pages. Result: a blank llm-wiki, ready to push.</p>
<p>Those pages make the wiki self-describing:</p>
<ul>
<li><strong>SCHEMA</strong>: the conventions, page format, required frontmatter, and the typed links between pages.</li>
<li><strong>index</strong>: the catalog of every page, the wiki’s table of contents.</li>
<li><strong>log</strong>: the append-only, dated record of what was done, by who and using which agent.</li>
</ul>
<p>Each is namespaced to the project (<code>index_codex-llm-wiki-test</code>, <code>SCHEMA_codex-llm-wiki-test</code>, <code>log_codex-llm-wiki-test</code>), so pages stay unambiguous when wikis are shared or merged.</p>
<div class="callout-highlight">
<p>The wiki is a separate repo from your code. Code and artifacts live in the project; durable knowledge lives in <code>.llm-wiki/</code>.</p>
</div>
<aside class="notes">
<p>If GitHub reports the wiki is unavailable, enable the repo wiki and create its first page, then rerun init. Show the two-history point: git -C .llm-wiki log is separate from the code repo.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="demo-3-ingest-the-alphafold-paper" class="slide level2 smaller">
<h2>Demo 3: ingest the AlphaFold paper</h2>
<p><span class="kicker">wiki-source: one paper, five pages</span></p>
<p><strong>Ingest</strong> turns an external source into wiki pages: the agent reads it and writes summarized, linked, cited pages. <strong>AlphaFold</strong> is DeepMind’s protein-structure predictor; our source is its 2021 Nature paper.</p>
<div class="columns">
<div class="column" style="width:52%;">
<div class="ed-term"><div><span class="cmd">ingest paper AlphaFold-Protein-Structure-2021.pdf</span></div><div><span class="pass">+ source summary + 4 concept pages</span></div></div>
<p>Plain language is enough: asking to <em>ingest</em> makes Codex call the <code>$llm-wiki:wiki-source</code> skill.</p>
<p>One ingest produced a <strong>source summary</strong> plus four linked concept pages:</p>
<ul>
<li><strong>Architecture</strong> — Evoformer and structure module.</li>
<li><strong>Training and data</strong> — datasets and training cutoff.</li>
<li><strong>Evaluation and confidence</strong> — the pLDDT and pTM metrics.</li>
<li><strong>Limitations and inference</strong> — where it is unreliable.</li>
<li>All <strong>cross-linked wiki style</strong>, with links typed where the relationship is clear.</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="ed-tip">
<p><strong>Pages, not chunks.</strong> Preserve what a future reader needs: dataset scope, training cutoffs, named methods, exact metrics, confidence intervals, limitations. A number without a source page does not exist for the project.</p>
</div>
<div class="callout-highlight">
<p>The ingested pages integrate into the existing wiki: related pages are updated, any contradiction with what the wiki already claims is reconciled, and back-references are fixed both ways. The ingest is recorded in the index and log, then a verification gate checks every page for unsupported claims and missing provenance before it is committed.</p>
</div>
</div></div>
<aside class="notes">
<p>For a PDF, the PDF skill extracts text and figures. The pattern: capture detail a future session will need, so the wiki answers without re-reading the paper.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="demo-4-run-alphafold-on-chignolin" class="slide level2 smaller">
<h2>Demo 4: run AlphaFold on chignolin</h2>
<p><span class="kicker">A ten-residue mini-protein: GYDPETGTWG</span></p>
<p>The power of AI removes friction and accelerates understanding. Just from the paper, I can test the ideas by getting Codex to find the code repository, install the software, and run it locally without intervention. In this demonstration I asked it to find a small molecule (it suggested chignolin) and get it to fold it.</p>
<div class="columns">
<div class="column" style="width:56%;">
<p>ColabFold 1.6.2, AlphaFold2 pTM, single-sequence MSA, five models, seed 0, three recycles, CPU.</p>
<div class="ed-term"><div><span class="cmd">JAX_PLATFORMS=cpu colabfold_batch chignolin.fasta results/</span></div><div><span class="cmd">  --msa-mode single_sequence --model-type alphafold2_ptm</span></div><div><span class="cmd">  --num-models 5 --num-recycle 3 --random-seed 0 --max-msa 1:1</span></div><div><span class="pass">ranked PDB + pLDDT/PAE plots + run log</span></div></div>
</div><div class="column" style="width:44%;">
<table class="ed-mini caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Output</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean pLDDT (10 res)</td>
<td>93.4</td>
</tr>
<tr class="even">
<td>pTM</td>
<td>0.06</td>
</tr>
<tr class="odd">
<td>Max aligned error</td>
<td>5.35 Å</td>
</tr>
</tbody>
</table>
</div></div>
<div class="callout-highlight">
<p>High pLDDT is confident local geometry; pTM 0.06 is poor global-fold confidence, expected here because a single-sequence MSA gives AlphaFold no evolutionary signal. These are model outputs, not experimental validation.</p>
</div>
<div class="ed-tip">
<p><strong>Experiment skill.</strong> The llm-wiki plugin includes an Experiment skill that documents an activity like this as a scientific experiment. It is called silently when a run produces results worth keeping.</p>
</div>
<aside class="notes">
<p>Chignolin is small and fast, with a known beta-hairpin folded state. The test is structure prediction, not folding kinetics or a free-energy landscape. The honest caveat on pTM is the point: the wiki records the metric and its limit together.</p>
<p>Exact run (for Q&amp;A). Full command: <code>MPLCONFIGDIR=/tmp/chignolin-mpl JAX_PLATFORMS=cpu .venv-colabfold/bin/colabfold_batch experiments/chignolin-prediction/chignolin.fasta experiments/chignolin-prediction/results --msa-mode single_sequence --model-type alphafold2_ptm --num-models 5 --num-recycle 3 --random-seed 0 --max-msa 1:1 --data .cache-colabfold</code>. Input FASTA: <code>&gt;chignolin / GYDPETGTWG</code>. Inspect the outputs with <code>find experiments/chignolin-prediction/results -maxdepth 2 -type f -print | sort</code>, then a small <code>python3</code> json reader over <code>*scores*.json</code> / <code>*rank_001*.json</code> for <code>ptm</code>, <code>iptm</code>, <code>mean_plddt</code>, <code>max_pae</code>. Measured: mean pLDDT 93.4, pTM 0.06, max PAE 5.34765625 Angstrom. Outputs in <code>experiments/chignolin-prediction/results/</code>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="demo-5-the-result-becomes-a-wiki-page" class="slide level2 smaller">
<h2>Demo 5: the result becomes a wiki page</h2>
<p><span class="kicker">Run in, durable page out</span></p>
<div class="columns">
<div class="column" style="width:42%;">
<p><img class="ed-img" src="slide-assets/chignolin-before-after.png" alt="Chignolin before and after AlphaFold prediction"></p>
<p>One plain-language line produced the figure:</p>
<blockquote>
<p><em>can you generate a pre and post image for the molecule?</em></p>
</blockquote>
<p>Codex used its built-in image tool to make this unfolded → folded illustration of chignolin.</p>
</div><div class="column" style="width:58%;">
<p><code>$llm-wiki:wiki-experiment</code> filed <strong>Chignolin-AlphaFold-Prediction</strong>. The skill:</p>
<ul>
<li>captures the <strong>configuration and metrics</strong>: parameters, seeds, dataset, headline numbers;</li>
<li>keeps the <strong>interpretation limits with the numbers</strong>, filing results honestly;</li>
<li>notes <strong>what changed</strong> vs.&nbsp;a previous run, and anything surprising;</li>
<li>records <strong>provenance</strong>: links to the results directory and the commit;</li>
<li><strong>integrates</strong> with related pages and reconciles contradictions;</li>
<li>updates the <strong>index and log</strong>, runs the <strong>verification gate</strong>, then commits.</li>
</ul>
<div class="ed-tip">
<p><strong>Live page:</strong> <code>github.com/chrissweet/codex-llm-wiki-test/wiki</code></p>
</div>
</div></div>
<aside class="notes">
<p>End of demo. The run, its numbers, and its images are now one linked, queryable page, not scattered files that vanish when the session ends. Hand to the payoff: does this memory actually work?</p>
<p>The before/after image is an AI-generated illustration: asked to “generate a pre and post image for the molecule,” Codex used its image-generation tool to make a side-by-side unfolded/folded depiction of chignolin (beta-hairpin), saved to experiments/chignolin-prediction/chignolin-before-after.png. It is explicitly not a measured folding trajectory, an MD result, or a rendering of the AlphaFold PDB.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="more-skills-maintain-share-consult" class="slide level2 smaller">
<h2>More skills: maintain, share, consult</h2>
<p><span class="kicker">Beyond building the wiki</span></p>
<p>Building the wiki is the start. Three more skills keep it healthy and connect it to other projects:</p>
<ul>
<li><strong><code>wiki-lint</code></strong> — a health check over the wiki: finds orphan pages, dead links, stale claims, missing frontmatter, and one-way cross-references, then offers fixes. Keeps the compounding memory honest as it grows.</li>
<li><strong><code>wiki-enroll</code></strong> — publishes an agent Card and a discovery topic so this wiki becomes findable by peer llm-wiki agents in the federation.</li>
<li><strong><code>wiki-ask</code></strong> — consults another project’s wiki via the <em>ask</em> primitive: it clones that agent’s wiki and queries it, so you draw on another project’s durable memory without leaving your session.</li>
</ul>
<div class="callout-highlight">
<p>One wiki you maintain (lint), publish (enroll), and query across (ask): durable memory that compounds and connects.</p>
</div>
<aside class="notes">
<p>These round out the toolkit. wiki-lint is the periodic health pass (orphans, dead links, stale claims, missing back-references, run every several sessions or after a big ingest). wiki-enroll makes the repo discoverable in the LA3D federation by writing a Card and adding the nd-llm-wiki topic. wiki-ask is the federation consumer: clone-and-invoke another agent’s wiki to answer a question from its memory, direct mode (name the agent) or discovery mode (pick from candidates). Not covered here: message/post async modes are not part of ask.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="turning-results-into-knowledge" class="slide level2 smaller">
<h2>Turning results into knowledge</h2>
<p><span class="kicker">The discipline, made concrete</span></p>
<style>
.reveal .ctl-box { background:#14213d; color:#fff; border-radius:6px; padding:0.5em 0.65em; height:100%; box-sizing:border-box; font-family:"Helvetica Neue",Arial,sans-serif; }
.reveal .ctl-box strong { display:block; color:#d4a835; font-size:0.86em; margin-bottom:0.25em; }
.reveal .ctl-box span { color:#cdd6e0; font-size:0.74em; line-height:1.32; }
.reveal .ed-flow { display:flex; align-items:stretch; gap:0.3em; margin:0.5em 0 0.35em; }
.reveal .ed-flow .step { flex:1; background:#f4f1ea; border:1px solid #d8cfb6; border-top:3px solid #b8860b; border-radius:6px; padding:0.4em 0.5em; font-size:0.74em; line-height:1.3; text-align:left; }
.reveal .ed-flow .step b { display:block; color:#14213d; font-size:1.05em; margin-bottom:0.15em; }
.reveal .ed-flow .step span { color:#5a4a4a; }
.reveal .ed-flow .arrow { align-self:center; color:#b8860b; font-weight:800; font-size:1em; }
.reveal .ctl-row { display:flex; gap:0.4em; align-items:stretch; margin-top:0.35em; }
.reveal .ctl-row .ctl-box { flex:1; height:auto; }
</style>
<p>Trustworthy results are not automatic enforcement; they come from encoded discipline the agent follows, plus reminders, run by the harness:</p>
<div class="ctl-row"><div class="ctl-box"><strong>1 · Real-output guidance</strong><span>use real outputs; scope every number to its corpus; report failures truthfully</span></div><div class="ctl-box"><strong>2 · Verification gate</strong><span>before committing, the agent re-reads each page against a checklist and fixes failures</span></div><div class="ctl-box"><strong>3 · Discipline gates</strong><span>a named list of always-wrong shortcuts the agent must reject</span></div><div class="ctl-box"><strong>4 · Advisory hooks</strong><span>session-start and post-edit hooks inject context and reminders; the gate does the content check</span></div></div>
<p><strong>How it runs, one loop:</strong></p>
<div class="ed-flow"><div class="step"><b>1 · Session start</b><span>a hook loads the guidance + the wiki's index and recent log into the agent</span></div><div class="arrow">→</div><div class="step"><b>2 · Work</b><span>skills carry the read and write procedures for pages</span></div><div class="arrow">→</div><div class="step"><b>3 · After an edit</b><span>a hook reminds; the agent runs the gate and fixes failures</span></div><div class="arrow">→</div><div class="step"><b>4 · Commit</b><span>to git; plain Markdown, so every step is auditable</span></div></div>
<p><em>A chat app runs none of this loop, which is why we build in Codex and Claude Code.</em></p>
<aside class="notes">
<p>Corrected against Codex for accuracy on both harnesses: these are agent-followed discipline plus advisory reminders, not automated blocking. Box 1 guidance lives in the plugin (<code>core/templates/guidance.md</code>, <code>core/agents/discipline-gates.md</code>, skill instructions), injected at session start. Box 2 verification gate is an agent-run pre-commit checklist (<code>core/agents/verification-gate.md</code>): re-read each page, apply the criteria, fix, then commit, not an automatic blocker. Box 3 discipline-gates names the “Universal Rationalizations (Always Wrong)”. Box 4: the PostToolUse hook is advisory and exits 0, it does not inspect content or block writes, it only reminds the agent to run the gate; headless <code>codex exec</code> runs no hooks and is a separate mode. This slide is the payoff of the epistemic-discipline setup on “What epistemic discipline is”, and it precedes the measurement so the zero fabrications arrives already explained.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="does-the-memory-actually-work" class="slide level2 smaller">
<h2>Does the memory actually work?</h2>
<p><span class="kicker">Two measurements: head to head, and at scale</span></p>
<p>Forty questions on one real project: reading the llm-wiki answered <strong>90% correctly and fabricated nothing</strong>, roughly double RAG’s 42% (10 fabrications); no-context scored 2%. And accuracy holds as the wiki grows to thousands of pages.</p>
<div class="columns">
<div class="column" style="width:46%;">
<p><strong>Head to head</strong> (n=40, one project, blind judge)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Approach</th>
<th>Correct</th>
<th>Overall</th>
<th>Fabr.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model alone</td>
<td>2%</td>
<td>0.10</td>
<td>2</td>
</tr>
<tr class="even">
<td>Plain RAG</td>
<td>42%</td>
<td>1.32</td>
<td>10</td>
</tr>
<tr class="odd">
<td><strong>llm-wiki</strong></td>
<td><strong>90%</strong></td>
<td><strong>2.65</strong></td>
<td><strong>0</strong></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:54%;">
<p><strong>At scale</strong> (500 to 4,000 real pages, Sonnet 5)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">pages</th>
<th style="text-align: right;">recall</th>
<th style="text-align: right;">reads</th>
<th style="text-align: right;">greps</th>
<th style="text-align: right;">index</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">500</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">90 KB</td>
</tr>
<tr class="even">
<td style="text-align: right;">1,077</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">199 KB</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2,028</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">384 KB</td>
</tr>
<tr class="even">
<td style="text-align: right;">4,013</td>
<td style="text-align: right;">98%</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">778 KB</td>
</tr>
</tbody>
</table>
</div></div>
<div class="callout-highlight">
<p>Recall stays near-perfect across 8x growth, and per-query cost stays flat, because the agent greps the index rather than reading it whole (retrieval is O(1) in corpus size).</p>
</div>
<aside class="notes">
<p>Head-to-head source: the WGRA post “llm-wiki vs RAG” and Wiki-vs-RAG-First-Run-Results / Cross-Model-Wiki-Reading. n=40 on one real research project, blind judge; 90% vs RAG’s 42%, a perfect 3.00 on method/judgment questions, zero fabrications; model-alone 2% shows the wiki adds the value. Scaling source: <code>llm-wiki-test-harness/docs/scaling-report.md</code> (Chris Sweet, 2026-09-08), real Sonnet 5 query runs (not projections) over 500 to 4,013 real arXiv pages around a 12-paper gold set; current one-line index; recall by gold-keyword match on specific-fact questions. Headline: recall flat (100% to 98%) and per-query cost bounded (3-6 reads, 5-7 greps) across 8x growth because the agent greps the index. The two panels are DIFFERENT experiments (blind-judge QA vs retrieval-recall) and are labeled as such; do not merge the numbers.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="this-wiki-mapped-to-a-knowledge-graph" class="slide level2 smaller">
<h2>This wiki, mapped to a Knowledge Graph</h2>
<iframe src="slide-assets/wiki-graph.html" style="width:100%; height:625px; border:none; border-radius:6px;"></iframe>
<span class="ed-cap">Generated by the wiki-kg plugin from the LA3D-LLM-Agents/llm-wiki-marketplace</span>
<aside class="notes">
<p>The interactive graph of this project’s own wiki, generated by the wiki-kg / wiki-graph-viz plugin we built this session. Drag nodes to explore, search by name, and color by type or by recency (git dates). Same structure a reader gets from the GitHub wiki; the typed edges are topology, not the query path.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-llm-wiki-marketplace" class="slide level2 smaller">
<h2>The llm-wiki marketplace</h2>
<p><span class="kicker">Extra tooling, installed like the core plugin</span></p>
<p>Our own marketplace, <strong><code>LA3D-LLM-Agents/llm-wiki-marketplace</code></strong>, ships the extras alongside the core llm-wiki plugin, dual Codex and Claude Code.</p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><strong><code>wiki-kg</code></strong> — build, query, and <strong>visualize</strong> a typed-edge knowledge graph from a wiki (rdflib + pyshacl, in-process). The map on the last slide came from here.</li>
<li><strong><code>wiki-agent-msg</code></strong> — cross-harness live messaging: list and message Claude Code and Codex sessions on the same machine.</li>
</ul>
</div><div class="column" style="width:50%;">
<p>Install like the core plugin:</p>
<div class="ed-term"><div><span class="cmd">$ codex plugin marketplace add LA3D-LLM-Agents/llm-wiki-marketplace</span></div><div><span class="cmd">$ codex plugin add wiki-kg@llm-wiki-marketplace</span></div></div>
<p>Claude Code: <code>/plugin marketplace add LA3D-LLM-Agents/llm-wiki-marketplace</code> then <code>/plugin install wiki-kg@llm-wiki-marketplace</code>.</p>
</div></div>
<p>Each page becomes typed RDF, so the wiki is a graph you can draw (above) or query with SPARQL:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource turtle number-lines code-with-copy"><code class="sourceCode"><span id="cb1-1"><a href=""></a>@prefix wiki: &lt;https://la3d.github.io/llm-wiki-colab/page/&gt; .</span>
<span id="cb1-2"><a href=""></a>@prefix kg:   &lt;https://la3d.github.io/llm-wiki-colab/ontology#&gt; .</span>
<span id="cb1-3"><a href=""></a></span>
<span id="cb1-4"><a href=""></a>wiki:Constraining-the-Field-for-Trust a kg:Synthesis ;</span>
<span id="cb1-5"><a href=""></a>    dcterms:title "Constraining-the-Field-for-Trust" ;</span>
<span id="cb1-6"><a href=""></a>    kg:extends   wiki:Lightweight-Structural-Graphs ;</span>
<span id="cb1-7"><a href=""></a>    kg:mentions  wiki:LLM-Wiki-Read-Path , wiki:Vision .</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Verified against the marketplace repo: LA3D-LLM-Agents/llm-wiki-marketplace lists two plugins, wiki-kg (build/query/visualize the KG) and wiki-agent-msg (cross-harness messaging), with a shared plugin tree carrying both <code>.claude-plugin</code> and <code>.codex-plugin</code> manifests. Same marketplace-add / plugin-add pattern as the core plugin from llm-wiki-colab; swap the plugin name. This is where the graph on the previous slide came from. The Turtle snippet is a real node from the graph-full.ttl wiki-kg produced for this wiki (Constraining-the-Field-for-Trust: type Synthesis, extends Lightweight-Structural-Graphs, mentions LLM-Wiki-Read-Path/Vision); only the ontology prefix was renamed ns1: to kg: and the mentions list trimmed for legibility.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="questions" class="slide level2 center">
<h2>Questions</h2>
<p><span class="kicker">Thank you</span></p>
<p><strong>Agentic research workflows.</strong> In one Codex session we installed the plugin, built a durable llm-wiki, ingested a paper, ran a real AlphaFold prediction, and recorded it as a linked, queryable page. That discipline turns results into knowledge you can trust, and it measurably works: it beat plain RAG with zero fabrications, and held near-perfect recall to thousands of pages.</p>
<p>Build one: <code>github.com/chrissweet/codex-llm-wiki-test/wiki</code></p>
<p>Chris Sweet, Charles Vardeman, Priscila Moreira, James Sweet</p>
<aside class="notes">
<p>Close. Point back at the public wiki as the thing they can go build today: github.com/chrissweet/codex-llm-wiki-test/wiki. Offer the tutorial guide as the step-by-step.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>la3d.github.io/WGRA</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="agentic-research-workflows_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="agentic-research-workflows_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="agentic-research-workflows_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="agentic-research-workflows_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="agentic-research-workflows_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="agentic-research-workflows_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="agentic-research-workflows_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="agentic-research-workflows_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="agentic-research-workflows_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="agentic-research-workflows_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>