<!DOCTYPE html>
<html lang="en"><head>
<script src="epistemic-discipline_files/libs/clipboard/clipboard.min.js"></script>
<script src="epistemic-discipline_files/libs/quarto-html/tabby.min.js"></script>
<script src="epistemic-discipline_files/libs/quarto-html/popper.min.js"></script>
<script src="epistemic-discipline_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="epistemic-discipline_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="epistemic-discipline_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="epistemic-discipline_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Chris Sweet">
  <meta name="author" content="Charles Vardeman">
  <meta name="author" content="Paul Brenner">
  <meta name="author" content="Evan Brinkman">
  <meta name="dcterms.date" content="2026-08-28">
  <title>Epistemic Discipline, Encoded</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="epistemic-discipline_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="epistemic-discipline_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="epistemic-discipline_files/libs/revealjs/dist/theme/quarto-00d918fe3ce335e2c1d542d2fc53de8b.css">
  <link href="epistemic-discipline_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="epistemic-discipline_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="epistemic-discipline_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="epistemic-discipline_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <style>
  .reveal .ed-img{ display:block; margin:0 auto; max-width:100%; max-height:400px; border:1px solid #d8cfb6; border-radius:4px; }
  .reveal #title-slide .quarto-title-authors{ transform:translateX(-2em); }
  .reveal .ed-quote{ font-size:1.15em; font-weight:600; color:#14213d; line-height:1.35; border-left:5px solid #b8860b; padding:.15em 0 .15em .7em; margin:.35em 0; font-style:italic; }
  .reveal .ed-quote .src{ display:block; font-size:.42em; font-style:normal; color:#8a7a4a; margin-top:.4em; }
  .reveal .ed-tip{ background:rgba(13,102,110,.09); border-left:5px solid #0d666e; border-radius:6px; padding:.3em .75em; margin:.35em 0; font-size:.82em; }
  .reveal .ed-tip strong{ color:#0d666e; text-transform:uppercase; letter-spacing:.04em; }
  .reveal .ed-tip code{ background:rgba(13,102,110,.12); color:#0d666e; padding:0 .25em; border-radius:3px; }
  .reveal .ed-probs-h{ text-align:center; color:#a13a30; font-weight:800; text-transform:uppercase; letter-spacing:.08em; font-size:.5em; margin:.35em 0 .15em; }
  .reveal .ed-probs{ display:flex; flex-direction:column; gap:.45em; }
  .reveal .ed-prob{ background:rgba(161,58,48,.08); border-left:5px solid #a13a30; border-radius:6px; padding:.4em .75em; font-size:.82em; line-height:1.35; text-align:left; }
  .reveal .ed-prob strong{ color:#a13a30; }
  .reveal .ed-prob .ex{ font-size:.86em; margin-top:.4em; color:#5a4a4a; }
  .reveal .ed-prob .ex b{ color:#a13a30; }
  .reveal .ed-fig{ text-align:left; }
  .reveal .ed-req{ width:100%; border-collapse:collapse; font-size:.52em; }
  .reveal .ed-req th{ text-align:left; font-size:.85em; text-transform:uppercase; letter-spacing:.05em; color:#b8860b; border-bottom:2px solid #b8860b; padding:.3em .5em; }
  .reveal .ed-req td{ padding:.45em .5em; border-bottom:1px solid #e2d3a8; vertical-align:top; }
  .reveal .ed-req .req{ font-weight:700; color:#14213d; }
  .reveal .ed-req .prac{ color:#0d666e; font-weight:600; }
  .reveal .ed-logcard{ background:#fbf9f3; border:1px solid #d8cfb6; border-left:4px solid #b8860b; border-radius:6px; padding:.6em .8em; font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.64em; line-height:1.45; color:#2c2c2c; box-shadow:0 2px 10px rgba(0,0,0,.07); }
  .reveal .ed-logcard .h{ font-weight:700; color:#14213d; }
  .reveal .ed-logcard .by{ color:#8a7a4a; font-style:italic; }
  .reveal .ed-logcard ul{ margin:.35em 0 0; padding-left:1.05em; }
  .reveal .ed-logcard li{ margin-bottom:.3em; }
  .reveal .ed-cap{ display:block; margin-top:.35em; font-size:.9em; font-style:italic; color:#8a7a4a; }
  .reveal .ed-deadcard{ background:#f7eeee; border:1px solid #d8b6b6; border-left:4px solid #a13a30; border-radius:6px; padding:.5em .7em; margin-top:.6em; font-family:ui-monospace,Menlo,monospace; font-size:.64em; line-height:1.45; color:#3a2222; }
  .reveal .ed-deadcard .h{ font-weight:800; color:#a13a30; letter-spacing:.08em; text-transform:uppercase; font-size:.85em; }
  .reveal .ed-term{ background:#0b1020; border:1px solid #24314c; border-radius:8px; padding:.8em 1em; font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.68em; line-height:1.5; color:#cdd6e4; box-shadow:0 10px 28px rgba(0,0,0,.45); }
  .reveal .ed-term .cmd{ color:#7683a0; }
  .reveal .ed-term .mut{ color:#e0a44b; font-weight:700; }
  .reveal .ed-term .fail{ color:#ff6b6b; font-weight:700; }
  .reveal .ed-term .rev{ color:#7683a0; }
  .reveal .ed-term .pass{ color:#6ee0a0; font-weight:700; }
  .reveal .ed-tmpl{ display:grid; grid-template-columns:1fr 1fr; gap:.55em; font-size:.8em; text-align:left; }
  .reveal .ed-card{ background:#fff; border:1px solid #d8cfb6; border-top:3px solid #b8860b; border-radius:6px; padding:.55em .65em; box-shadow:0 2px 8px rgba(0,0,0,.06); }
  .reveal .ed-card .t{ font-weight:800; color:#b8860b; text-transform:uppercase; letter-spacing:.04em; font-size:.85em; margin-bottom:.35em; }
  .reveal .ed-card .kv{ margin:.12em 0; } .reveal .ed-card .kv b{ color:#14213d; }
  .reveal .ed-card.mono{ font-family:ui-monospace,Menlo,monospace; }
  .reveal .ed-mini{ width:100%; border-collapse:collapse; font-family:ui-monospace,Menlo,monospace; }
  .reveal .ed-mini th{ text-align:left; color:#b8860b; border-bottom:1px solid #d8cfb6; padding:.12em .3em; font-size:.95em; }
  .reveal .ed-mini td{ padding:.12em .3em; border-bottom:1px solid #eee; color:#333; }
  .reveal .ed-surf{ display:flex; gap:.2em; } .reveal .ed-surf span{ flex:1; text-align:center; background:#eef1f7; border:1px solid #14213d; border-radius:3px; padding:.15em; font-size:.9em; color:#14213d; }
  .reveal .ed-surf span.frozen{ background:#f0ece0; color:#8a7a4a; border-color:#d8cfb6; }
  .reveal .ed-corr{ text-align:left; font-size:.5em; }
  .reveal .ed-corr li{ margin-bottom:.5em; }
  .reveal .ed-corr .ck{ color:#2c7a54; font-weight:800; }
  </style>
  <script>
  document.addEventListener('DOMContentLoaded', function () {
    function injectKicker() {
      var ts = document.getElementById('title-slide');
      if (!ts) { setTimeout(injectKicker, 100); return; }
      if (ts.querySelector('.title-kicker')) return;
      var k = document.createElement('div');
      k.className = 'title-kicker';
      k.textContent = 'Doing science with AI';
      ts.insertBefore(k, ts.firstChild);
    }
    injectKicker();
  });
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#14213d" class="quarto-title-block center">
  <h1 class="title">Epistemic Discipline, Encoded</h1>
  <p class="subtitle">How to know things when an AI does much of the work</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Chris Sweet 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Charles Vardeman 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Paul Brenner 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Evan Brinkman 
</div>
</div>
</div>

  <p class="date">August 28, 2026</p>
</section>
<section id="the-bottleneck-moved" class="slide level2 smaller">
<h2>The bottleneck moved</h2>
<p><span class="kicker">The problem with a fast, plausible collaborator</span></p>
<p>Research used to be a loop: form a hypothesis, write the code, analyze the data, test the hypothesis, revise the conclusions, and go round again, many times over. Producing each result was the slow part.</p>
<p>AI now appears to remove that bottleneck. It writes complex code, carries a vast working knowledge of statistics and analysis methods, and returns test results ready to present.</p>
<div class="callout-highlight">
<p>So the bottleneck of research is no longer producing results. It is knowing which results deserve belief.</p>
</div>
<p><strong>Plausibility is the enemy.</strong> From our own project record, the AI describing its own failure, verbatim:</p>
<div class="ed-quote">
<p>“The worst failure of this project: I built a tractable proxy instead of the user’s hypothesis, and let loose language hide the substitution.” <span class="src">Lessons-Learned.md, project wiki, 2026-08-19, surfaced only when the user queried</span></p>
</div>
<p>Nothing was wrong with the output. It ran, it passed, it read well. It just was not the thing we set out to know.</p>
<div class="ed-tip">
<p><strong>Tip 1.</strong> Get the LLM to write and keep a <code>Lessons-Learned.md</code>. The quote above is from ours.</p>
</div>
<aside class="notes">
<p>Open cold with the quote if comfortable. Land in the first minute: this failure was caught, recorded by the AI in its own words, and became a rule. The talk is about the machinery that makes that the normal outcome, not a lucky catch. Do not name the domain yet; the problem is universal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-epistemic-discipline-is" class="slide level2 smaller">
<h2>What epistemic discipline is</h2>
<p><span class="kicker">Four requirements you already believe in</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="callout-highlight">
<p>One way to solve this is <strong>epistemic discipline</strong>: turning a produced result into something you actually <em>know</em>, justified rather than merely generated. In practice, the pre-committed rules that decide what evidence must exist, and in what order it must be produced, before a claim enters the record.</p>
</div>
<p>You already practice this. Each requirement is a standard scientific habit.</p>
</div><div class="column" style="width:50%;">
<table class="ed-req caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">The requirement</th>
<th data-quarto-table-cell-role="th">What you already call it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="req">Provenance.</span> a claim carries where it came from</td>
<td class="prac">citation</td>
</tr>
<tr class="even">
<td><span class="req">Pre-commitment.</span> targets and margins declared before the data arrives</td>
<td class="prac">pre-registration</td>
</tr>
<tr class="odd">
<td><span class="req">Witnessed failure.</span> a test counts only if you saw it fail when it should</td>
<td class="prac">a positive control</td>
</tr>
<tr class="even">
<td><span class="req">Durable memory.</span> what was tried, decided, and abandoned is written down</td>
<td class="prac">a lab notebook</td>
</tr>
</tbody>
</table>
</div></div>
<div class="ed-probs-h">AI problems</div>
<div class="ed-probs">
<div class="ed-prob">These live in habits, and AI speed breaks habits. When results arrive in minutes, the habits are the first thing skipped.<div class="ex"><b>Seen here:</b> the wiki and the plan both recorded a stage as "built and done." Running it crashed on a missing field (KeyError). The habit, run it and inspect the output, had been skipped; the false claim survived until someone ran the code.</div></div>
<div class="ed-prob">Picture what we know as a surface that research nudges forward by a small step, an <em>epsilon</em> that preserves everything already verified. AI defaults to the opposite, discarding and regenerating work at each step, without the discipline to take small, preserving steps.<div class="ex"><b>Seen here:</b> asked to consolidate three reports into one paper, it regenerated rather than preserved, and the draft did not even describe the MPP, the framework the reports exist to present. Filed as a dead end.</div><div class="ex"><b>In miniature:</b> we had agreed the severity space must stay continuous; at build time it computed the continuous score and then bucketed it into four discrete levels, throwing the agreed design away.</div></div>
</div>
<aside class="notes">
<p>The philosophical center and the definition slide for the title. Say explicitly: the claim is not that AI needs new epistemology. It is that AI-speed research needs the old epistemology made mechanical, because no one, human or AI, keeps habits at that pace. AI-problem example sources: built-without-running (Lessons-Learned.md, “A plotting script is not a generator”; the stage was missing five fields and crashed on KeyError trigger_kinds); consolidation lost the MPP framework (Capabilities-Ledger.md dead ends); continuous score bucketed to four levels (Lessons-Learned.md, “Carry the agreed abstraction into the build”, 2026-08-19). Two more for Q&amp;A, both caught by the process: the unfaithful replay, same-law samples read instead of the actual disk members (log, 2026-08-23 correction), and the inert mutation, a check that could not fail accepted green until a real corruption reddened it (log, 2026-08-24, C4).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="encode-it-do-not-remember-it" class="slide level2 smaller">
<h2>Encode it, do not remember it</h2>
<p><span class="kicker">The move: discipline as artifacts, not intentions</span></p>
<div class="columns">
<div class="column" style="width:58%;">
<p>Move each requirement out of your head and into an artifact the process enforces.</p>
<ul>
<li><strong>Memory</strong> lives in a project wiki the AI reads to recall and writes to remember: llm-wiki.</li>
<li><strong>The gates</strong> live in rule files the AI must follow: no green counts without a witnessed red, no number enters without verification at the cited source, no measurement before its margins are declared.</li>
<li><strong>The control surface</strong> lives in a charter the human owns: what is protected, what is out of scope, what a plan must state before work starts.</li>
</ul>
<p>The process refuses the shortcut, so no one has to decline it.</p>
<p>Running example: a statistics project, 13 days, generating ontology-valid synthetic scenarios calibrated to published studies. Five prototypes, 102 wiki pages, 119 log entries, a 188-test suite. All data synthetic.</p>
</div><div class="column" style="width:42%;">
<p><img class="ed-img" src="slide-assets/ed-system-diagram.png" alt="Two-loop system diagram: a generation loop and a calibration loop around the ontology"></p>
</div></div>
<aside class="notes">
<p>One sentence on the domain and move on; the synthetic frame is stated here once. The next three slides are the howto: one artifact class per slide, with the literal template on screen. Source: counts on wiki/prism_synthesis.wiki/, log_prism_synthesis.md, suite on P5-Stage-2-Hazard-Machinery.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="howto-memory-that-compounds" class="slide level2 smaller">
<h2>Howto: memory that compounds</h2>
<p><span class="kicker">The wiki is the lab notebook, and the AI keeps it</span></p>
<div class="columns">
<div class="column" style="width:55%;">
<p>Three page types do the work. The formats are copyable:</p>
<ul>
<li><strong>A log entry:</strong> date, type, subject, attribution, then bullets. Types across our 119 entries: 20 experiment, 19 ingest, 11 decision, 5 correction.</li>
<li><strong>A dead end:</strong> what was tried, and the reason it failed. Re-entry requires addressing the reason. Nine on our books; none re-entered.</li>
<li><strong>A source page:</strong> a published number, the page it was verified on, and its scope caveats. A number without this page does not exist for the project.</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="ed-fig"><div class="ed-logcard"><div class="h">## [2026-08-23] experiment | Move 3.2 (Bernecker concealment) ACCEPTED</div><div class="by">- by: Chris Sweet via claude-code</div><ul><li>Corpus p3m2 (n=1000, zero violations): concealment ratio 3.647 vs target 3.0 (inside source CI 1.8 to 5.0); holdout null 1.476 [0.609, 3.579]</li><li>Headline: the record can now lie (recorded tier differs from latent tier; solve against the recorded tier)</li></ul></div><div class="ed-deadcard"><div class="h">Dead end</div>Rejection sampling as the coherence mechanism (deleted and mislabeled the acute-after-presentation class) → constructive conditioning</div></div>
</div></div>
<p>What this buys: sessions resume where they left off, decisions are cited instead of re-litigated, and the same mistake is not paid for twice.</p>
<div class="callout-highlight">
<p>Memory that compounds already exists as tools like <strong>llm-wiki</strong>: a persistent, interlinked memory attached to the LLM. The AI reads it to recall at the start of a session and writes to it to remember at the end, so what the project knows lives in the artifact, not in a chat window that vanishes when the session ends.</p>
</div>
<aside class="notes">
<p>How is this different from RAG over your papers? The wiki stores syntheses, decisions, and verdicts with provenance and current status (confirmed, superseded, dead end); a stale claim gets flagged and corrected, not re-retrieved forever. Sources: log_prism_synthesis.md type counts; Capabilities-Ledger.md dead ends.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="howto-the-gates" class="slide level2 smaller">
<h2>Howto: the gates</h2>
<p><span class="kicker">No green without a witnessed red</span></p>
<div class="columns">
<div class="column" style="width:55%;">
<p>The rule, from the project’s rules file: evidence is only evidence if it could have come out the other way. The procedure, four steps, mechanical:</p>
<ol type="1">
<li>Write the check. If it passes on first run, you have learned nothing yet.</li>
<li>Corrupt the exact thing the check guards. Watch it fail, for that reason.</li>
<li>Revert. Watch it pass.</li>
<li>Record all three observations.</li>
</ol>
</div><div class="column" style="width:45%;">
<div class="ed-fig"><div class="ed-term"><div><span class="cmd">$ pytest -q test_known_deltas</span></div><div><span class="pass">4 passed</span></div><div>&nbsp;</div><div><span class="cmd">$ mutate: negate the selection filter</span></div><div><span class="mut">MUTATED</span> <span class="cmd">filter negated</span></div><div><span class="cmd">$ pytest -q test_known_deltas</span></div><div><span class="fail">FAILED</span> test_known_deltas: <span class="fail">assert 0 == 4</span></div><div><span class="cmd">$ git checkout -- .   # revert</span></div><div><span class="rev">REVERTED</span></div><div><span class="cmd">$ pytest -q test_known_deltas</span></div><div><span class="pass">4 passed</span></div></div></div>
</div></div>
<p>A green you cannot show the red for is a green you have not earned. Two more gates, same spirit: margins and targets are committed before the data is generated, and a literature number enters only after being re-read at the cited page.</p>
<div class="callout-highlight">
<p>The gates exist in tools like <strong>llm-wiki</strong>: rule files the LLM must follow. The discipline, no green without a witnessed red, every number verified at its source, margins declared before measuring, is enforced by the process, not left to anyone remembering to apply it.</p>
</div>
<aside class="notes">
<p>Tie back to slide 2: this is a positive control plus pre-registration, mechanized. Q&amp;A depth: the record also holds an honest case where a mutation did NOT redden one test because its expectation routed through the corrupted formula; the docstring now says what it actually guards (P5-Stage-2-Hazard-Machinery.md). Sources: assert 0 == 4 on P5-Stage-1-Time-To-Repeat.md commit 416074e; two citation errors caught (table cited p.&nbsp;37, found p.&nbsp;38), log 2026-08-28.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="howto-the-humans-control-surface" class="slide level2 smaller">
<h2>Howto: the human’s control surface</h2>
<p><span class="kicker">What you write down so the AI cannot drift</span></p>
<div class="columns">
<div class="column" style="width:42%;">
<p>Templates that the scientist maintains:</p>
<ul>
<li><strong>A charter</strong> with two tiers: inviolate rules, and rulings (standing scope decisions, each with the condition that reopens it).</li>
<li><strong>A five-line plan contract</strong> at the top of every plan. Consent applies to those five lines.</li>
<li><strong>A protected ledger</strong> of working capabilities. Replacement requires demonstrated equivalence first.</li>
<li><strong>A declared modification surface</strong> before each phase; the rest frozen at a git tag.</li>
</ul>
</div><div class="column" style="width:58%;">
<div class="ed-tmpl"><div class="ed-card mono"><div class="t">Charter ruling</div><div class="kv"><b>R2:</b> classifier out of scope</div><div class="kv"><b>Expires when:</b> SBIR accord with colleagues AND substantial calibration exist</div><div class="kv" style="color:#8a7a4a">applied and cited, never re-asked</div></div><div class="ed-card mono"><div class="t">Five-line plan contract</div><div class="kv"><b>goal:</b> add umbrella sampling</div><div class="kv"><b>added:</b> tilted sampler + analytic weights</div><div class="kv"><b>REMOVED:</b> none</div><div class="kv"><b>risky:</b> random-stream change</div><div class="kv"><b>untouched:</b> default corpus (bit-identical)</div></div><div class="ed-card"><div class="t">Protected ledger row</div>
<table class="ed-mini caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">capability</th>
<th data-quarto-table-cell-role="th">where</th>
<th data-quarto-table-cell-role="th">verified by</th>
<th data-quarto-table-cell-role="th">status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C8: concealment as disclosure downgrade (A15-A17)</td>
<td>spec draw + fit_calibration</td>
<td>ratio RED 1.097, green 3.09 (n=60k)</td>
<td>ACTIVE</td>
</tr>
</tbody>
</table>
</div><div class="ed-card"><div class="t">Declared modification surface</div><div class="ed-surf"><span>Ontology</span><span>ODP</span><span>Draw code</span><span>Calibration</span><span class="frozen">Untouched</span></div><div class="kv" style="color:#8a7a4a;margin-top:.35em">which artifacts change; the rest frozen at a git tag</div></div></div>
</div></div>
<p><strong>What only the human does:</strong> set the goal, adopt or defer, scope, judge which ideas have supporting data.</p>
<div class="callout-highlight">
<p>The control surface lives in llm-wiki too: the charter, ledger, and rulings are pages the AI reads at the start of every session, so it works inside the structure instead of around it.</p>
</div>
<aside class="notes">
<p>The slide that must actually TELL them how. Walk each card in one sentence; someone can photograph it and reproduce the structure. The deep answer to “who does the science”: the human owns everything here; the AI owns execution and verification labor inside it. Sources: R2 from Charter.md; five-line contract from the user-level CLAUDE.md; ledger columns and 24 rows from Capabilities-Ledger.md; modification-surface columns from Prototype-Registry.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-loop-corrects-itself" class="slide level2 smaller">
<h2>The loop corrects itself</h2>
<p><span class="kicker">The test of a knowledge process: can it retire its own beliefs?</span></p>
<div class="columns">
<div class="column" style="width:52%;">
<p><strong>Episode one:</strong> a number we invented, refuted by evidence, filed without a fight. A behavioral gradient was set at ratio 2.33 from expert interviews, always carrying the label “ours alone, no published source”. When two independent DoD sources were ingested and verified at the page, they put it at 1.2 to 1.3, and the probability sample’s entire confidence interval excluded our value. The record now reads: direction confirmed, magnitude refuted, revision scoped as the next move.</p>
<div class="ed-fig"><svg viewbox="0 0 430 210" style="width:100%;max-height:230px;font-family:ui-monospace,Menlo,monospace"><line x1="55" y1="176" x2="395" y2="176" stroke="#bbb" stroke-width="1"></line><line x1="60.0" y1="173" x2="60.0" y2="179" stroke="#bbb"></line><text x="60.0" y="192" font-size="9" fill="#888" text-anchor="middle">1.0</text><line x1="166.7" y1="173" x2="166.7" y2="179" stroke="#bbb"></line><text x="166.7" y="192" font-size="9" fill="#888" text-anchor="middle">1.5</text><line x1="273.3" y1="173" x2="273.3" y2="179" stroke="#bbb"></line><text x="273.3" y="192" font-size="9" fill="#888" text-anchor="middle">2.0</text><line x1="380.0" y1="173" x2="380.0" y2="179" stroke="#bbb"></line><text x="380.0" y="192" font-size="9" fill="#888" text-anchor="middle">2.5</text><line x1="343.7" y1="34" x2="343.7" y2="176" stroke="#a13a30" stroke-width="1.5" stroke-dasharray="4 3"></line><circle cx="343.7" cy="50" r="6" fill="#a13a30"></circle><text x="331.7" y="53" font-size="10" fill="#a13a30" text-anchor="end" font-weight="700">ours (interviews) 2.33</text><rect x="72.8" y="96" width="70.4" height="8" rx="2" fill="#14213d" opacity="0.28"></rect><circle cx="109.1" cy="100" r="5" fill="#14213d"></circle><text x="151.2" y="103" font-size="10" fill="#14213d" text-anchor="start">probability sample  1.23 (CI 1.06 to 1.39)</text><circle cx="106.9" cy="140" r="5" fill="#14213d"></circle><text x="116.9" y="143" font-size="10" fill="#14213d" text-anchor="start">second survey  1.22</text><text x="225" y="207" font-size="9.5" fill="#a13a30" text-anchor="middle" font-style="italic">the 2.33 assumption sits outside the evidence</text></svg></div>
</div><div class="column" style="width:48%;">
<div class="ed-corr"><b>Episode two: corrected before the code existed.</b><ul><li><span class="ck">✓</span> a missing preservation tag surfaced</li><li><span class="ck">✓</span> a math argument that did not transfer between model laws</li><li><span class="ck">✓</span> a planned test that was null by construction and could never have failed</li></ul><div style="color:#8a7a4a">process catches what enthusiasm would ship</div></div>
</div></div>
<aside class="notes">
<p>Keep the domain abstract (“a behavioral gradient”); name it if asked. The philosophical point: a process that can only accumulate beliefs is not a knowledge process. A recorded, unresisted retirement of a belief is the strongest evidence the discipline is real. Sources: assumed 2.33 from derivegen/spec.py CONCEAL_P, Stakeholder-Interviews-2026-06.md; PERSEREC 2018 OR 1.48 [1.11,1.97], risk ratio ~1.23 [1.06,1.39], n=14,088, Table 6; LIS 2022 1.22; B2 corrections in log 2026-08-28.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-payoff-ideas-become-cheap" class="slide level2 smaller">
<h2>The payoff: ideas become cheap</h2>
<p><span class="kicker">Safety is what makes trying inexpensive</span></p>
<div class="columns">
<div class="column" style="width:52%;">
<p>Mid-conversation, the domain scientist: in molecular dynamics we use umbrella sampling to see rare states without waiting for them. Could we do that here?</p>
<p>Same day, it existed: the sampler tilted toward the rare classes, corrected with analytic weights, and, the part that matters, proven bit-for-bit identical to the frozen system with the feature off.</p>
<p>Measured: weighted base rate 0.1085 against the 0.10 design, effective sample size 1,837, and the held-out null association stayed null at 0.846, interval 0.593 to 1.207, now at 847 rare-class members instead of about 100.</p>
<p>The lesson is not speed. A cross-domain idea got a fair trial because the preservation proof made trying it reversible, and reversible is what makes it cheap.</p>
</div><div class="column" style="width:48%;">
<p><img class="ed-img" src="slide-assets/ed-alignment-forest.png" alt="Alignment forest: planted targets with intervals, the umbrella rows at tightened precision"></p>
</div></div>
<aside class="notes">
<p>Umbrella sampling citation if asked: Torrie and Valleau 1977. This answers “what do I get for all this discipline”: the freedom to try things, because every trial is provably reversible. Connect to slide 6: pinned prototypes and the ledger make reversibility a checkout, not archaeology. Source: P4-Move-1-Umbrella-Corpus.md, corpus_out_u1 umbrella-summary.json.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="getting-started" class="slide level2 smaller">
<h2>Getting started</h2>
<p><span class="kicker">The minimal kit, priced honestly</span></p>
<p>You do not need our whole apparatus. The starter kit is four artifacts:</p>
<ol type="1">
<li><strong>A project wiki</strong> the AI reads at session start and writes at session end. llm-wiki gives you this with the schema and gates built in.</li>
<li><strong>One rules file:</strong> no green without a witnessed red; no number without verification at source; declare targets before measuring.</li>
<li><strong>One charter page:</strong> the goal, what is protected, your standing scope decisions with their reopening conditions.</li>
<li><strong>A log habit:</strong> every session ends with dated, typed entries, including the failures.</li>
</ol>
<p>The costs, stated plainly: the discipline is real work, the wiki needs maintenance, and the gates slow the happy path on purpose.</p>
<div class="callout-highlight">
<p>The claim is not that AI made the research fast. It is that this structure made fast research trustworthy.</p>
</div>
<aside class="notes">
<p>End on costs; it buys credibility. Q&amp;A: team scale (llm-wiki has a multi-writer push protocol, lightly exercised); model dependence (the wiki is model-agnostic content; an external review by a different AI session was addressed item by item); human time (Chris speaks to this; the record captures outcomes, not hours).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="backup-slides" class="slide level2 center">
<h2>Backup slides</h2>
</section>
<section id="backup-the-case-study-in-numbers" class="slide level2 smaller">
<h2>Backup: the case study in numbers</h2>
<p><span class="kicker">The running example, quantified</span></p>
<p>Thirteen days, 2026-08-16 to 28. The peak, August 23, is the day five literature-calibrated mechanisms landed, each with its baseline observed red first: 0.170 vs target 0.4535; 1.097 before 3.09; 0.997 before green.</p>
<div class="ed-fig"><svg viewbox="0 0 920 300" style="width:100%;max-height:430px;font-family:ui-monospace,Menlo,monospace"><line x1="42" y1="264" x2="892" y2="264" stroke="#bbb"></line><rect x="54.4" y="205.0" width="40.5" height="59.0" rx="2" fill="#14213d"></rect><text x="74.7" y="202.0" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">9</text><text x="74.7" y="277.0" font-size="9" fill="#888" text-anchor="middle">16</text><rect x="119.8" y="250.9" width="40.5" height="13.1" rx="2" fill="#14213d"></rect><text x="140.1" y="247.9" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">2</text><text x="140.1" y="277.0" font-size="9" fill="#888" text-anchor="middle">17</text><text x="205.5" y="277.0" font-size="9" fill="#888" text-anchor="middle">18</text><rect x="250.6" y="257.4" width="40.5" height="6.6" rx="2" fill="#14213d"></rect><text x="270.8" y="254.4" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">1</text><text x="270.8" y="277.0" font-size="9" fill="#888" text-anchor="middle">19</text><rect x="316.0" y="178.8" width="40.5" height="85.2" rx="2" fill="#14213d"></rect><text x="336.2" y="175.8" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">13</text><text x="336.2" y="277.0" font-size="9" fill="#888" text-anchor="middle">20</text><rect x="381.3" y="152.6" width="40.5" height="111.4" rx="2" fill="#14213d"></rect><text x="401.6" y="149.6" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">17</text><text x="401.6" y="277.0" font-size="9" fill="#888" text-anchor="middle">21</text><text x="401.6" y="26.0" font-size="8" fill="#0d666e" text-anchor="middle" font-weight="700">P1/2</text><rect x="446.7" y="152.6" width="40.5" height="111.4" rx="2" fill="#14213d"></rect><text x="467.0" y="149.6" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">17</text><text x="467.0" y="277.0" font-size="9" fill="#888" text-anchor="middle">22</text><text x="467.0" y="26.0" font-size="8" fill="#0d666e" text-anchor="middle" font-weight="700">P1/2</text><rect x="512.1" y="28.0" width="40.5" height="236.0" rx="2" fill="#b8860b"></rect><text x="532.4" y="25.0" font-size="9" fill="#b8860b" text-anchor="middle" font-weight="700">36</text><text x="532.4" y="277.0" font-size="9" fill="#888" text-anchor="middle">23</text><text x="532.4" y="26.0" font-size="8" fill="#0d666e" text-anchor="middle" font-weight="700">P3</text><rect x="577.5" y="211.6" width="40.5" height="52.4" rx="2" fill="#14213d"></rect><text x="597.8" y="208.6" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">8</text><text x="597.8" y="277.0" font-size="9" fill="#888" text-anchor="middle">24</text><text x="597.8" y="26.0" font-size="8" fill="#0d666e" text-anchor="middle" font-weight="700">P4</text><text x="663.2" y="277.0" font-size="9" fill="#888" text-anchor="middle">25</text><rect x="708.3" y="211.6" width="40.5" height="52.4" rx="2" fill="#14213d"></rect><text x="728.5" y="208.6" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">8</text><text x="728.5" y="277.0" font-size="9" fill="#888" text-anchor="middle">26</text><text x="728.5" y="26.0" font-size="8" fill="#0d666e" text-anchor="middle" font-weight="700">reports</text><rect x="773.7" y="250.9" width="40.5" height="13.1" rx="2" fill="#14213d"></rect><text x="793.9" y="247.9" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">2</text><text x="793.9" y="277.0" font-size="9" fill="#888" text-anchor="middle">27</text><rect x="839.0" y="224.7" width="40.5" height="39.3" rx="2" fill="#14213d"></rect><text x="859.3" y="221.7" font-size="9" fill="#14213d" text-anchor="middle" font-weight="700">6</text><text x="859.3" y="277.0" font-size="9" fill="#888" text-anchor="middle">28</text><text x="859.3" y="26.0" font-size="8" fill="#0d666e" text-anchor="middle" font-weight="700">P5</text><text x="42" y="294" font-size="10" fill="#888">Log entries per day, August 16 to 28. Peak Aug 23 (36): five calibrated mechanisms landed, prototype 3 closed.</text></svg></div>
<aside class="notes">
<p>Use if the room wants the speed story; keep the framing “cadence enabled by discipline”. Source: per-day counts from log_prism_synthesis.md; the three red-first baselines, Capabilities-Ledger.md rows C7 to C9.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="backup-the-formalism-and-its-null" class="slide level2 smaller">
<h2>Backup: the formalism and its null</h2>
<p><span class="kicker">Solve, then measure, then try to fail</span></p>
<div class="columns">
<div class="column" style="width:52%;">
<p>Scenarios are marked point processes; every statistic is computed from re-parsed output graphs, never from generator state. Calibration is solve-then-measure with a pre-declared held-out association (published odds ratio 12.9) that must measure null. It did: 0.879 with interval 0.74 to 1.04 at prototype 1, and 0.846 with interval 0.593 to 1.207 at umbrella precision.</p>
</div><div class="column" style="width:48%;">
<p><img class="ed-img" src="slide-assets/ed-mpp-distribution-v9.png" alt="Measured marked-point-process distribution of corpus v9"></p>
</div></div>
<aside class="notes">
<p>For the statistician asking how calibration avoids circularity: the holdout is the answer, and it is declared before any corpus. Sources: 0.879 [0.74,1.04] Prototype-Registry.md; 0.846 [0.593,1.207] P4-Move-1-Umbrella-Corpus.md; published 12.9 MSMR-Non-Medical-Risk-Factors-2025.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="backup-what-the-ontology-adds" class="slide level2 smaller">
<h2>Backup: what the ontology adds</h2>
<p><span class="kicker">Construction, not generate-and-test</span></p>
<div class="columns">
<div class="column" style="width:52%;">
<p>One ontology design pattern is the single semantic authority. The sampler draws free choices; a reasoner completes the entailments; validation is an always-pass contract, so a violation is a bug, not a rejection. Zero rejections means the corpus distribution is exactly the sampler’s law, which is what makes the calibration argument sound.</p>
</div><div class="column" style="width:48%;">
<p><img class="ed-img" src="slide-assets/ed-odp-graph.png" alt="Ontology design pattern graph"></p>
</div></div>
<aside class="notes">
<p>For the knowledge-representation audience member. Sources: zero rejections, delete-a-shape and planted-violation proofs, Prototype-Registry.md prototype 2; hybrid reasoning 3.3x speedup, Capabilities-Ledger.md row E3.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>la3d.github.io/WGRA</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="epistemic-discipline_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="epistemic-discipline_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="epistemic-discipline_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="epistemic-discipline_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="epistemic-discipline_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="epistemic-discipline_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="epistemic-discipline_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="epistemic-discipline_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="epistemic-discipline_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="epistemic-discipline_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>